### ISSUE TITLE
Europe average item amount sold not pulling from api

### ISSUE THREAD

**Issue by Kappamenhehe** [ao-data/albiondata-client#102]
just like in Topic,
idk if its devs issue with new update or what

**Comment by Kappamenhehe** [comment]
nevermind , yesterday europe.albion-online-data.com was working now it need to be www.europe

**Comment by Kappamenhehe** [comment]
Yes , i just realized now that whole api isn't working , sorry for problem

**Comment by phendryx** [comment]
The api is definitely working. Again, not sure what you're talking about.
