### ISSUE TITLE
No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by Mihass2** [ao-data/albiondata-client#105]
No connection could be made because the target machine actively refused it.
![image](https://github.com/ao-data/albiondata-client/assets/169338612/90abd24c-0e5c-494e-a01d-da65568f2784)

**Comment by phendryx** [comment]
Honestly, try again and see what happens. That sounds like the AODP server was busy at the moment and wasn't accepting new connections. It happens a few times a day for about 30 seconds while I'm working on some new code. I don't know 100% if this is the issue causing your error, but if you try again and it works, that's likely it.
