### ISSUE TITLE
query of item now only returns default qualities=1 instead of all qualities

### ISSUE THREAD

**Issue by gsiisg** [ao-data/albiondata-client#108]
is the missing other qualities from 2-4 missing on purpose?  It used to return all qualities...

**Comment by bonished** [comment]
> is the missing other qualities from 2-4 missing on purpose? It used to return all qualities...

you are wrong sir - &qualities=0 returns all qualities, 1 returns Normal only.
hope that helps :)

**Comment by phendryx** [comment]
Actually, the old software did, in fact, used to return all when you sent in no qualities.

**Comment by gsiisg** [comment]
@bonished I see, I verified 0 works to return the old behavior
@phendryx thanks for verifying that I didn't make a mistake
