### ISSUE TITLE
New items when?

### ISSUE THREAD

**Issue by bonished** [ao-data/albiondata-client#109]
Hello, I've wanted to ask if and when new items will be available in AOD? It's been a while when they were released.
I'm talking about shapeshifting stuff and crystal weapons (eg. shapeshift staffs; tracking mats and artifacts; infinity blade; rift glaive and all the rest)
I don't want to hurry anybody but I just wanted to know is this even planned to be added in the near future?
Best regards

**Comment by phendryx** [comment]
If you're talking about bin dumps, everything is updated within a few hours of updates being released.
