### ISSUE TITLE
"Market data is encrypted. Please see https://discord.com/channels/336216450689794048/586173260564267028 for more information." - Discord Link not working

### ISSUE THREAD

**Issue by mbrey** [ao-data/albiondata-client#119]
I tried to run the client and when i open the in-game market the client throws "Market data is encrypted. Please see https://discord.com/channels/336216450689794048/586173260564267028 for more information.". It is not possible to access this discord channel.

**Comment by phendryx** [comment]
Its a public channel on the AODP discord.
