### ISSUE TITLE
Progress Indication

### ISSUE THREAD

**Issue by nbourg8** [ao-data/albiondata-client#14]
I'm apparently too fast in the market. Eventually I rack up enough "Sending 50 market offers to ingest" messages that I start getting errors. Can you include a counter for those "Sending 50 market offers to ingest" messages and have a feedback counter for when we receive "Successfully sent ingest request to http://www.albion-online-data.com:4223"

That way I know all my data has been sent and I can more effectively time my data pulls.

**Comment by kochd** [comment]
> (...) I start getting errors

Like 902?
https://www.albion-online-data.com/#client-is-getting-902-error-code

Here are your rate limits:
https://github.com/ao-data/albiondata-gate/blob/main/config.rb#L4

**Comment by phendryx** [comment]
Kochd linked the faq and the config showing the rate limits.

Having watched the stats for a few months, there's very few 902's overall. The amount of work to have the server return either a) how many hits you currently have in a rolling time range or b) how many hits you have left in a rolling time range and then updating the client to display that is too much work when it's actually somewhat hard to hit that rate limit when manually typing and/or copying/pasting text to search for in the market.

**Comment by kochd** [comment]
>  -no-limit
>    	Use all available CPU cores

You could run the client with the "-no-limit" parameter, which puts more stress on your CPU but you'll be able to submit more data.

**Comment by nbourg8** [comment]
@phendryx @kochd Sorry for the late reply. I will push it again and see. I was not typing each search in, but rather using the market navigation menus to cycle through all the tiers/enchants for every resource item (T1_WOOD, T2_WOOD, T3_WOOD, etc..)

**Comment by nbourg8** [comment]
> @phendryx @kochd Sorry for the late reply. I will push it again and see. I was not typing each search in, but rather using the market navigation menus to cycle through all the tiers/enchants for every resource item (T1_WOOD, T2_WOOD, T3_WOOD, etc..) . Yes they were 902 errors.

Well I just did an entire city's market of resources. I got several 902 errors as I was much faster than the messages were being sent. 
![image](https://user-images.githubusercontent.com/24832335/219479881-a3d3b0aa-fb2b-404f-9b5d-97112fb4b7a9.png)

**Comment by kochd** [comment]
We had issues with people sending faked data in mass on purpose. Therefore we took actions to make sending a massive amount of updates impossible. That's what you are seeing. 
 
Running the application with the `-no-limit` parameter doubles your potential output.

https://www.digitalcitizen.life/shortcut-arguments-parameters-windows/
