### ISSUE TITLE
Error in Pow Get request: Get "http://www.albion-online-data.com:4223/pow"

### ISSUE THREAD

**Issue by MikolasKage** [ao-data/albiondata-client#15]
Hello, sorry for newbie question, but it isn't working for me.
1) When I've installed it 1st time I've had the same problem as here [https://github.com/regner/albiondata-client/issues/96](url)
Solved this, by deleting Winpcap and installing https://npcap.com
2) Every time I'm opening Market I've got this:

`INFO[2023-02-12T00:15:02+07:00] Sending 50 market offers to ingest
ERRO[2023-02-12T00:15:02+07:00] Error in Pow Get request: Get "http://www.albion-online-data.com:4223/pow": read tcp 192.168.0.163:49296->138.197.64.234:4223: wsarecv: An existing connection was forcibly closed by the remote host.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x13de1aa]

goroutine 16 [running]:
github.com/broderickhyman/albiondata-client/client.(*httpUploaderPow).uploadWithPow(0xc0001880d8, 0x0, 0x0, 0x0, 0x0, 0xc0002695c0, 0x10, 0xc0005ce000, 0x2ad2, 0x3000, ...)
        /home/runner/work/albiondata-client/albiondata-client/client/uploader_http_pow.go:81 +0x34a
github.com/broderickhyman/albiondata-client/client.(*httpUploaderPow).sendToIngest(0xc0001880d8, 0xc0005ce000, 0x2ad2, 0x3000, 0x1546df3, 0x13)
        /home/runner/work/albiondata-client/albiondata-client/client/uploader_http_pow.go:134 +0x11c
github.com/broderickhyman/albiondata-client/client.sendMsgToUploaders(0xc0005ce000, 0x2ad2, 0x3000, 0x1546df3, 0x13, 0xc000184340, 0x1, 0x1)
        /home/runner/work/albiondata-client/albiondata-client/client/dispatcher.go:116 +0xb5
github.com/broderickhyman/albiondata-client/client.sendMsgToPublicUploaders(0x149e260, 0xc000004bd0, 0x1546df3, 0x13, 0xc0001e2000)
        /home/runner/work/albiondata-client/albiondata-client/client/dispatcher.go:68 +0x1ea
github.com/broderickhyman/albiondata-client/client.operationAuctionGetOffersResponse.Process(0xc000225880, 0x32, 0x32, 0xc0001e2000)
        /home/runner/work/albiondata-client/albiondata-client/client/operation_auction_get_offers.go:58 +0x3c5
created by github.com/broderickhyman/albiondata-client/client.(*Router).run
        /home/runner/work/albiondata-client/albiondata-client/client/router.go:52 +0x2ad`

What can I do to solve this?

**Comment by phendryx** [comment]
What happens if you hit http://www.albion-online-data.com:4223/pow with a browser?

**Comment by MikolasKage** [comment]
> What happens if you hit http://www.albion-online-data.com:4223/pow with a browser?

"This site can’t be reached"

**Comment by phendryx** [comment]
Ok, then there's something going on with either your internet connection or your DNS server(s). You should be getting a response that looks something like this `{"wanted":"0011100101100001011000010011010000111","key":"bb6387"}`. If you're computer can't reach the server, the client won't be able to either.

**Comment by BloodShadel** [comment]
same problem, but i have response from http://www.albion-online-data.com:4223/pow

**Comment by Gonz1g** [comment]
Doesn't work for me either,same error while checking price Error in Pow Get request: Get "http://www.albion-online-data.com:4223/pow

**Comment by Gonz1g** [comment]
> @Gonz1g post output please.

Same as the creator of the post

**Comment by phendryx** [comment]
Can you put http://www.albion-online-data.com:4223/pow in a browser and see what it says?

**Comment by Gonz1g** [comment]
> 

![image](https://user-images.githubusercontent.com/100488515/219207044-8f72be18-ddde-4052-a90f-45f96ce4bc8d.png)

**Comment by phendryx** [comment]
@Gonz1g I asked what happens when you put http://www.albion-online-data.com:4223/pow in a browser like Chrome, Firefox, Safari, etc. Trying to determine if its the game client or if its a connectivity issue.

**Comment by Gonz1g** [comment]
> @Gonz1g I asked what happens when you put http://www.albion-online-data.com:4223/pow in a browser like Chrome, Firefox, Safari, etc. Trying to determine if its the game client or if its a connectivity issue.

nvm,i got the info,that because im from Russia,and the ports,that programm is using are blocked right now.VPN doesnt work too,cuz the client does not see all the data from the game at all (for example, moving from location to location).

**Comment by phendryx** [comment]
Closing this since its VPN related.

**Comment by MikolasKage** [comment]
> 

So, did you find a way how to make it work?

With VPN enabled I can reach http://www.albion-online-data.com:4223/pow, but when I came to the Market - there is nothing in the console.
In -debug mode such errors running endlessly
![image](https://user-images.githubusercontent.com/91815149/219827584-f6afdd9c-b56a-4f9e-a6c7-0da576a6a812.png)

**Comment by phendryx** [comment]
Those errors aren't really errors. We just don't know what those events are and they are not being parsed by the client. Running with -debug is basically just "show me all the incoming events/operations".

As for VPN, no, I haven't looked into that and honestly probably won't myself. If someone else figures it out, hopefully they post something about it.

**Comment by MikolasKage** [comment]
> 

Ok :) Thought you have an answer like "Turn port forwarding on the router and it will help" :D

**Comment by phendryx** [comment]
@MikolasKage Try going to the main site https://www.albion-online-data.com/. If that works, then try this: `albiondata-client.exe -i http+pow://pow.albion-online-data.com`.

**Comment by MikolasKage** [comment]
> @MikolasKage Try going to the main site https://www.albion-online-data.com/. If that works, then try this: `albiondata-client.exe -i http+pow://pow.albion-online-data.com`.

![image](https://user-images.githubusercontent.com/91815149/219959596-28ff85cc-9e88-4fe7-a93d-e133e005f9bf.png)
hmm, I think it's working! I don't even need to go out of village, it's working after login, by pressing on market!

**Comment by MikolasKage** [comment]
> > @Gonz1g I asked what happens when you put http://www.albion-online-data.com:4223/pow in a browser like Chrome, Firefox, Safari, etc. Trying to determine if its the game client or if its a connectivity issue.
> 
> nvm,i got the info,that because im from Russia,and the ports,that programm is using are blocked right now.VPN doesnt work too,cuz the client does not see all the data from the game at all (for example, moving from location to location).

Here is the solution

**Comment by phendryx** [comment]
Someone else had another issue just like yours and they couldnt hit the POW endpoint so... it was a weird port number so I figured I'd try to proxy it on the server.

Glad it worked!

@Gonz1g @BloodShadel For now, start the client like this: `albiondata-client.exe -i http+pow://pow.albion-online-data.com`. In a future update, I will make it that the proxied endpoint is default and you won't need to specify `-i`.
