### ISSUE TITLE
Client does not detect player/location change after recent game update

### ISSUE THREAD

**Issue by unsinedz** [ao-data/albiondata-client#18]
Recently Albion Online rolled out a new version with multi-region support. Albion Data Client stopped detecting player and location change.

Repro steps:
1. Run latest ao-data client.
2. Start Albion Online and log in.
3. Appear at any location.
4. (optional) Try changing location in the game

AR:
Player is not detected, there is no message in the console and scanning market prices results with errors in the console.

ER:
Player and location are detected. market prices can be scanned

**Comment by phendryx** [comment]
There was an update yesterday. I verified the client is still working as of this post (there was another small patch this morning). It's working as expected.

Please update your client. Reopen this issue if there is still a problem after updating your client.
