### ISSUE TITLE
error while loading shared libraries: libpcap.so.0.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by sova32** [ao-data/albiondata-client#41]
error while loading shared libraries: libpcap.so.0.8: cannot open shared object file: No such file or directory

**Comment by sova32** [comment]
linux

**Comment by phendryx** [comment]
No idea what flavor of linux you're running, but basically you need to install libpcap and then symlink that version back to 0.8. https://github.com/jclehner/nmrpflash/issues/27 has some examples of how to do that.

**Comment by sova32** [comment]
thanx, but i alrady install thats libriaris. sorry. i was found that i
need. And android application "albion online money maker" in playmarket
uxse our client to update market prices. but it have server reqest error.
maby your tool dont work because programmers from albion online was change
data transfer protocol. check this please. thank you for answer and sorry
me please! happy hollydays to you!

10 апр. 2023 г. 2:28 ПП пользователь "Paul Hendryx" <
***@***.***> написал:

**Comment by phendryx** [comment]
There's been no protocol changes since the east server release.
