### ISSUE TITLE
[Enhancement] Option to disable autostart

### ISSUE THREAD

**Issue by tyhawk** [ao-data/albiondata-client#42]
After installing, the client automatically starts with Windows, but I don't always need it. It would be nice to be able to disable autostart and simply start it myself whenever I need it.

Also, I wasn't able to find the autostart in my Windows configuration, so I haven't been able to disable this manually either.

**Comment by phendryx** [comment]
You can edit/disable startup of the data client in "Task Scheduler". In Windows 10/11, hit the start button and just type "Task Scheduler". It's likely the top item in the list.
