### ISSUE TITLE
Albion headless 24/7 price polling bot

### ISSUE THREAD

**Issue by lecatos** [ao-data/albiondata-client#44]
Need an independent Client that doesn't require to monitor existing gaming traffic. Basically the Client takes in login credential and Logins into the game by itself then the bot polls for all market prices of all item 24/7. By doing so, you can have multiple bot at all locations polling for actual real time prices while consuming little computer resources.

Current Api isn't advanced enough.

**Comment by wlndclion** [comment]
according to https://forum.albiononline.com/index.php/Thread/51604-Is-it-allowed-to-scan-your-internet-trafic-and-pick-up-logs/?postID=512670#post512670
ANSWER IS NO
newbee hum?

**Comment by lecatos** [comment]
Fine, i do it myself

**Comment by phendryx** [comment]
Please don't. If you decide to do that and you associate this project with it, then SBI could get cranky and make it very difficult this project to work at all.

On the other hand, you wan't to risk your own accounts and have that many computers, have a blast.

**Comment by lecatos** [comment]
Vpn + Virtual machine

**Comment by phendryx** [comment]
Locking this conversation, because this project is not interested in botting or non-official clients.
