### ISSUE TITLE
No option to remove from Windows Startup

### ISSUE THREAD

**Issue by goldern** [ao-data/albiondata-client#45]
Title says it all, the program keeps starting alongside Windows and there's no opt-out in Startup apps nor Albion Data Client 
![image](https://user-images.githubusercontent.com/5741155/235353339-bba9d239-30fa-464b-95a3-759ec42090e5.png)
![image](https://user-images.githubusercontent.com/5741155/235353349-48ac6b55-b461-4780-9892-54eeff971192.png)

**Comment by phendryx** [comment]
https://www.albion-online-data.com/#disable-start-with-windows
