### ISSUE TITLE
PANI[2023-05-03T06:33:57+08:00] Error opening adapter: �t�Χ䤣�����w���˸m�C (20)

### ISSUE THREAD

**Issue by bigbossbe** [ao-data/albiondata-client#46]
INFO[2023-05-03T06:33:57+08:00] Starting Albion Data Client, version: 0.1.29
INFO[2023-05-03T06:33:57+08:00] This is a third-party application and is in no way affiliated with Sandbox Interactive or Albion Online.
INFO[2023-05-03T06:33:57+08:00] Additional parameters can listed by calling this file with the -h parameter.
INFO[2023-05-03T06:33:57+08:00] Watching Albion
PANI[2023-05-03T06:33:57+08:00] Error opening adapter: �t�Χ䤣�����w���˸m�C (20)
panic: (*logrus.Entry) 0xc0002abd50

goroutine 37 [running]:
github.com/sirupsen/logrus.Entry.log(0xc000142000, 0xc000141aa0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/entry.go:255 +0x32d
github.com/sirupsen/logrus.(*Entry).Log(0xc0001420e0, 0x0, 0xc0001a3f80, 0x1, 0x1)
        /home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/entry.go:283 +0xf2
github.com/sirupsen/logrus.(*Entry).Panic(0xc0001420e0, 0xc0002d9f80, 0x1, 0x1)
        /home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/entry.go:321 +0x5c
github.com/broderickhyman/albiondata-client/log.Panic(...)
        /home/runner/work/albiondata-client/albiondata-client/log/logger.go:108
github.com/broderickhyman/albiondata-client/client.(*listener).startOnline(0xc000211d80, 0xc0001ac000, 0x32, 0x13c0)
        /home/runner/work/albiondata-client/albiondata-client/client/listener.go:39 +0xcd
created by github.com/broderickhyman/albiondata-client/client.(*albionProcessWatcher).createListeners
        /home/runner/work/albiondata-client/albiondata-client/client/albion_watcher.go:69 +0x193

When I run the albiondata-client.exe it shows these message.
I am using windows 11, traditional chinese lanuage.

**Comment by bigbossbe** [comment]
I changed my windows system lanuage, the error message shows:
INFO[2023-05-03T07:10:01+08:00] Starting Albion Data Client, version: 0.1.29
INFO[2023-05-03T07:10:01+08:00] This is a third-party application and is in no way affiliated with Sandbox Interactive or Albion Online.
INFO[2023-05-03T07:10:01+08:00] Additional parameters can listed by calling this file with the -h parameter.
INFO[2023-05-03T07:10:01+08:00] Watching Albion
PANI[2023-05-03T07:10:02+08:00] Error opening adapter: The system cannot find the device specified. (20)
panic: (*logrus.Entry) 0xc000143730

goroutine 36 [running]:
github.com/sirupsen/logrus.Entry.log(0xc000142000, 0xc000141aa0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/entry.go:255 +0x32d
github.com/sirupsen/logrus.(*Entry).Log(0xc0001420e0, 0x0, 0xc000305f80, 0x1, 0x1)
        /home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/entry.go:283 +0xf2
github.com/sirupsen/logrus.(*Entry).Panic(0xc0001420e0, 0xc0001c9f80, 0x1, 0x1)
        /home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/entry.go:321 +0x5c
github.com/broderickhyman/albiondata-client/log.Panic(...)
        /home/runner/work/albiondata-client/albiondata-client/log/logger.go:108
github.com/broderickhyman/albiondata-client/client.(*listener).startOnline(0xc00018a1c0, 0xc0001a4000, 0x32, 0x13c0)
        /home/runner/work/albiondata-client/albiondata-client/client/listener.go:39 +0xcd
created by github.com/broderickhyman/albiondata-client/client.(*albionProcessWatcher).createListeners
        /home/runner/work/albiondata-client/albiondata-client/client/albion_watcher.go:69 +0x193

**Comment by phendryx** [comment]
Have you followed the troubleshooting steps found at https://www.albion-online-data.com/#client-crashing?

**Comment by bigbossbe** [comment]
I think i found more information:

albiondata-client.exe -debug
INFO[2023-05-03T07:43:41+08:00] Starting Albion Data Client, version: 0.1.29
INFO[2023-05-03T07:43:41+08:00] This is a third-party application and is in no way affiliated with Sandbox Interactive or Albion Online.
INFO[2023-05-03T07:43:41+08:00] Additional parameters can listed by calling this file with the -h parameter.
INFO[2023-05-03T07:43:41+08:00] Watching Albion
DEBU[2023-05-03T07:43:41+08:00] Will listen to these devices: [\Device\NPF_{EC9A5E16-9FAF-4B9D-AEBB-E80BAEE646D7} \Device\NPF_{097FC355-AA18-4E64-ABA4-1AC00765BD2D}]
PANI[2023-05-03T07:43:41+08:00] Error opening adapter: The system cannot find the device specified. (20)
panic: (*logrus.Entry) 0xc000277f10

goroutine 9 [running]:
github.com/sirupsen/logrus.Entry.log(0xc0000f0000, 0xc0000eda70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/entry.go:255 +0x32d
github.com/sirupsen/logrus.(*Entry).Log(0xc0000f00e0, 0x0, 0xc0001a1f80, 0x1, 0x1)
        /home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/entry.go:283 +0xf2
github.com/sirupsen/logrus.(*Entry).Panic(0xc0000f00e0, 0xc000145f80, 0x1, 0x1)
        /home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/entry.go:321 +0x5c
Dgithub.com/broderickhyman/albiondata-client/log.Panic(...)
        /home/runner/work/albiondata-client/albiondata-client/log/logger.go:108
github.com/broderickhyman/albiondata-client/client.(*listener).startOnline(0xc0002f6280, 0xc00001ae80, 0x32, 0x13c0)
        E/home/runner/work/albiondata-client/albiondata-client/client/listener.go:39 +0xcd
Bcreated by github.com/broderickhyman/albiondata-client/client.(*albionProcessWatcher).createListeners
        /home/runner/work/albiondata-client/albiondata-client/client/albion_watcher.go:69 +0x193

---------------------------------------
i used dumpcap.exe -D to check my adapters:

dumpcap.exe -D
1. \Device\NPF_{BE2E7781-1AD9-4349-8492-50761961CA8D} (VMware Network Adapter VMnet8)
2. \Device\NPF_{C8D88A9F-8371-4514-9B97-FE0DEC3F8037} (Bluetooth)
3. \Device\NPF_{9EE4EA11-9051-4AE2-A66D-7E38A01B91D5} (VMware Network Adapter VMnet1)
4. \Device\NPF_{097FC355-AA18-4E64-ABA4-1AC00765BD2D} (HomeNetwork)
5. \Device\NPF_{723E6361-3B65-42FC-936B-737900B952E3} (SurfSharkVPN)

---------------------------------------
my internet adapter is 4. \Device\NPF_{097FC355-AA18-4E64-ABA4-1AC00765BD2D} (HomeNetwork)
i think the program selected a incorrect adapter.


may i know how to change it when i use albiondata-client?

**Comment by phendryx** [comment]
The link I provided above tells you how to get the mac address of the network adapter, in your case, "HomeNetwork" and how to tell the data client to use that mac address. I think the data client is failing on some other network adapter that isn't listed in dumpcap that ends with 646D7.
