### ISSUE TITLE
error while loading shared libraries: libpcap.so.0.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by sova32** [ao-data/albiondata-client#48]
error while loading shared libraries: libpcap.so.0.8: cannot open shared object file: No such file or directory
os linux arch based

**Comment by phendryx** [comment]
We already discussed this in https://github.com/ao-data/albiondata-client/issues/41.

**Comment by sova32** [comment]
You are stupid? libpcap.so.0.8 is installed in system!


чт, 11 мая 2023 г. в 15:37, Paul Hendryx ***@***.***>:

**Comment by phendryx** [comment]
And now that you're calling me stupid, I will actively NOT help you. Have a nice day :).
