### ISSUE TITLE
client crashing

### ISSUE THREAD

**Issue by azaru** [ao-data/albiondata-client#49]
ERRO[2023-05-21T19:04:10+02:00] Error while sending ingest to nats with data: nats: invalid connection
ERRO[2023-05-21T19:04:10+02:00] Error in Pow Get request: Get "http://www.albion-online-data.com:4223/pow": dial tcp: lookup www.albion-online-data.com: no such host
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x454cc05]

goroutine 1914 [running]:
github.com/broderickhyman/albiondata-client/client.(*httpUploaderPow).uploadWithPow(0xc0005fe340, 0x0, 0x0, 0x0, 0x0, 0xc001718f00, 0x10, 0xc001a9d000, 0x2bc5, 0x3000, ...)
	/usr/src/app/client/uploader_http_pow.go:92 +0x625
github.com/broderickhyman/albiondata-client/client.(*httpUploaderPow).sendToIngest(0xc0005fe340, 0xc001a9d000, 0x2bc5, 0x3000, 0x4773d60, 0x13, 0xc0001d4000)
	/usr/src/app/client/uploader_http_pow.go:147 +0x128
github.com/broderickhyman/albiondata-client/client.sendMsgToUploaders(0xc001a9d000, 0x2bc5, 0x3000, 0x4773d60, 0x13, 0xc001d62bc0, 0x3, 0x4, 0xc0001d4000)
	/usr/src/app/client/dispatcher.go:114 +0xbe
github.com/broderickhyman/albiondata-client/client.sendMsgToPublicUploaders(0x46a6540, 0xc0005e7be0, 0x4773d60, 0x13, 0xc0001d4000)
	/usr/src/app/client/dispatcher.go:65 +0x334
github.com/broderickhyman/albiondata-client/client.operationAuctionGetRequestsResponse.Process(0xc000116a80, 0x32, 0x32, 0xc0001d4000)
	/usr/src/app/client/operation_auction_get_requests.go:44 +0x375
created by github.com/broderickhyman/albiondata-client/client.(*Router).run
	/usr/src/app/client/router.go:52 +0x2d5
	
Running on Macos Ventura 13.4

**Comment by kochd** [comment]
As it says:
```
lookup [www.albion-online-data.com](http://www.albion-online-data.com/): no such host
```

Fix your dns / connection

**Comment by kochd** [comment]
If that's the case your connection to the internet is probably unstable.
