### ISSUE TITLE
Easy anticheat detected

### ISSUE THREAD

**Issue by scmanjarrez** [ao-data/albiondata-client#51]
Hi,
Do I need to do something special to run it in Windows? Easy anticheat disconnected my game

**Comment by scmanjarrez** [comment]
I was opening the client, not the launcher (which starts EAC service)

**Comment by phendryx** [comment]
If EAC was a problem with albion data project client, there'd be more complains here and discord. I suspect you have something else running that triggers EAC. I've had issues with both Albion and Rust detecting things that have nothing to do with gaming.

**Comment by scmanjarrez** [comment]
The problem was that I was launching directly from the client, not the launcher, so the EAC service didn't start and then it complains.
