### ISSUE TITLE
Item Enchantment Filter

### ISSUE THREAD

**Issue by flowxrc** [ao-data/albiondata-client#52]
It would be really useful to add a filter for Item Enchantments, I am not sure but it may be in the "UniqueName" value of the item object

**Comment by kochd** [comment]
Can you make more clear what you are talking about?
It's absolutely clear in the data what the enchantment level is. 

T4 flat:
https://www.albion-online-data.com/api/v2/stats/view/T4_BAG?locations=Martlock
T4.1:
https://www.albion-online-data.com/api/v2/stats/view/T4_BAG@1?locations=Martlock

**Comment by phendryx** [comment]
Closing to inactivity.
