### ISSUE TITLE
Date/Time Data has a 'T' in It

### ISSUE THREAD

**Issue by sadume** [ao-data/albiondata-client#57]
Date/Time Data has a 'T' in It

I'm not sure if this is something that can be fixed like if its from Albion end but it just makes the data annoying to work with in code.

`ValueError: time data '2023-08-24T12:10:00' does not match format '%y/%m/%d %H:%M:%S'`

**Comment by phendryx** [comment]
Any datetime parser will parse it just fine. https://en.wikipedia.org/wiki/ISO_8601

**Comment by kochd** [comment]
https://docs.python.org/3/library/datetime.html#datetime.datetime.fromisoformat
