### ISSUE TITLE
help? error cannot find player location

### ISSUE THREAD

**Issue by Loopstop** [ao-data/albiondata-client#64]
![Screenshot_1](https://github.com/ao-data/albiondata-client/assets/28827651/2dcda13b-4cae-4f78-86dd-0f50477a89ae)
i already tried to reinstall it, already installed npcap, when i download the data client it says a message saying that a newer version of wincap has been already detected, then it says aborting installation, i dont know if its related to albion data client though, but it installs data client anyways
the error happens when i open market, and yes, even if i change area it still doesnt work (atm i was testing it at caerleon, didnt tested in any other city)

**Comment by phendryx** [comment]
There was a game update today. Things are broken currently. The new data client is being worked on and should be released sometime today.
