### ISSUE TITLE
'Updating player location' repeating multiple times

### ISSUE THREAD

**Issue by LiPhlow** [ao-data/albiondata-client#66]
Sometimes after getting from one zone to another player location starts updating multiple times and if I change location one more time while this is happening things can get weird. Explanation on screenshot:
![albiondata-client_uOCdLEwuRS](https://github.com/ao-data/albiondata-client/assets/148381706/ef5a63e7-8074-4cf5-a123-13d8e5365327)

**Comment by phendryx** [comment]
Yeah, I mentioned this in discord. I haven't had a chance to dig back into it but it works ok-ish for the moment until I can look at it again.

**Comment by phendryx** [comment]
Resolved with #69 and #70. Release 0.1.32 contains the changes.
