### ISSUE TITLE
After trying to check prices for Chicken and Goat, the client gives an error and closes.

### ISSUE THREAD

**Issue by Googinot** [ao-data/albiondata-client#68]
![Снимок экрана 2023-10-23 215252](https://github.com/ao-data/albiondata-client/assets/93269843/9129b5ce-4c10-4fd5-841f-3997c93c528e)
Adding **-i** or **-no-limit** prefixes does not help
I suspect that the problem is not only mine, because... prices are not displayed on albiononline2d.com
https://albiononline2d.com/en/item/id/T3_FARM_CHICKEN_GROWN

**Comment by Googinot** [comment]
> Update your client running as admin. The url is wrong, when you update it should work

Does not help. The client closes itself after an error.
![image](https://github.com/ao-data/albiondata-client/assets/93269843/2f0dfc7e-e5c2-463f-9580-3a6b07e77c32)

**Comment by phendryx** [comment]
The url is fine. This was a open port issue. Cloudflare wanted money for "deep subdomains" like "pow.east.albion-online-data.com" so I removed Cloudflare from the mix and repointed those directly to the server. Except I didn't open http(80)/https(443) to everyone (vs just Cloudflare IPs). Result of fixing things before my work day stared and not having enough coffee.

**Comment by Googinot** [comment]
The following helped:
1) Running CMD as Administrator
2) Enter "C:\Program Files\Albion Data Client\albiondata-client.exe"
3) Proft!

**Comment by phendryx** [comment]
@Googinot I promise that has nothing to do with it and it has everything to do with the ports not being opened until a few minutes ago :).
