### ISSUE TITLE
Launch on Windows startup

### ISSUE THREAD

**Issue by yoyoda2048** [ao-data/albiondata-client#74]
Hi
I have version 0.1.32 on windows 11. It launches on startup but nothing happens in the console window when I play the game. In order for it to work, I have to close the console that launches on start-up and manually restart Albion Data Client and then everything works in the console but I can't hide it any more. Do you have a solution for me?
Regards

**Comment by phendryx** [comment]
Are you using a VPN to play the game?

**Comment by yoyoda2048** [comment]
Now I've got this error message sometimes on startup
![Capture d'écran 2023-11-05 110909](https://github.com/ao-data/albiondata-client/assets/120314258/6879405e-dab3-4e2b-8dc5-e8058b3cf639)

**Comment by yoyoda2048** [comment]
Hi
My problem is still there.
Is there at least a way to prevent Albion Data Client from launching when Windows starts?
Regards

**Comment by yoyoda2048** [comment]
Thanks
