### ISSUE TITLE
It's not catching market response

### ISSUE THREAD

**Issue by juzt3** [ao-data/albiondata-client#80]
may be they have changed the way they send this data

**Comment by phendryx** [comment]
https://discord.com/channels/336216450689794048/545608962930638868/1199703935557050498

![image](https://github.com/ao-data/albiondata-client/assets/482311/ebcd9ad6-8b66-4ce3-a52c-73bb22d41f78)

**Comment by gsiisg** [comment]
Is anyone able to or working to decrypt the datastream?

**Comment by cmg-divined** [comment]
> Is anyone able to or working to decrypt the datastream?

There are a few people trying to figure things out on Discord. Anyone is welcome to join in and help.
