### ISSUE TITLE
data from AH encrypted in last patch

### ISSUE THREAD

**Issue by madvac** [ao-data/albiondata-client#81]
it looks in last patch data from AH is encrypted.

**Comment by phendryx** [comment]
I guess I'll leave this one open... I replied in #80 about the same issue.

https://discord.com/channels/336216450689794048/545608962930638868/1199703935557050498

![image](https://github.com/ao-data/albiondata-client/assets/482311/ebcd9ad6-8b66-4ce3-a52c-73bb22d41f78)

**Comment by SandroMoretti** [comment]
hi @phendryx what is this discord from your screenshot?

I'm thinking about change my bot to listen history insteand current price... but I wanna check updates before do it, to prevent unecessary work... this discord is from albion online data? if yes can u send me? thank you.

**Comment by phendryx** [comment]
https://discord.gg/cV3cxkfn

Current pricing/live is encrypted now, some people are sending market history but far less data overall than what we had with current/live pricing.

**Comment by madvac** [comment]
its working again :-)

**Comment by xqoma** [comment]
> @madvac  its working again :-)

Is this still working or not again?

I'm trying to analyze game traffic using this albion-data-client repo, but it looks like the auction offer response data is encrypted.

But in the albion-online-data API prices are updated, which means someone is pushing them. Also, you said it started working again.

🤷🏼‍♂️

**Comment by JPCodeCraft** [comment]
It's encrypted for some people only. Use and older premium toon and it'll probably not be encrypted.
