### ISSUE TITLE
City parameter is returning numbers at times

### ISSUE THREAD

**Issue by gabrielsoaresgsm** [ao-data/albiondata-client#86]
Good evening, I have a question, I'm searching for an item "Major Gigantify Potion", the link: https://west.albion-online-data.com/api/v2/stats/prices/T7_POTION_REVIVE is returning citys: [ "3311", "5003"]

There are other items that return ['2333', '4000', '1000', '0', '1335', ​​'5002']

Are these numbers a city? Or is it really bugged?
![image](https://github.com/ao-data/albiondata-client/assets/77764654/3b54fdff-fbfc-40dc-b0fb-4a1a3e31558f)

**Comment by phendryx** [comment]
Technically, the cities are all numbers. There's a number to string conversion that happens for most of the main locations in the data project APIs. https://github.com/ao-data/ao-bin-dumps/blob/master/formatted/world.txt is a list of all the locations and the strings/names associated.
