### ISSUE TITLE
Client only recording player location but not items

### ISSUE THREAD

**Issue by Mcgeneral1987** [ao-data/albiondata-client#90]
Dear sir/madam,

I have used the Albion Online Data Client in the past. After returning to the game I downloaded the newest client (v.35). I run the application as admin, then start the game client afterwards. The client recognises my character, and the location it is in. However, when I open the marketplace and search for items, it does not record any items.

Any idea what might be causing this?

Version 1.0.35
Region: Albion Americas
![image](https://github.com/ao-data/albiondata-client/assets/27824317/7aee02d3-6b35-4727-a2c7-9644adaeebcf)

**Comment by phendryx** [comment]
https://github.com/ao-data/albiondata-client/issues/81.

TL;DR SBI at one point encrypted all market data. Then after working with us, made it so that some people get unencrypted market data. We have no idea what criteria is required for unencrypted data, except that we know for sure that newer accounts/toons are definitely encrypted.

**Comment by phendryx** [comment]
If you were to open an items history or look at gold history, the AODP client will pick those up. It's just live/current market data that is sometimes encrypted/unencrypted based on unknown criteria.

**Comment by Mcgeneral1987** [comment]
Thanks for the quick reply. It's an interesting situation, since this character has definitely uploaded data before. Anyways, you say 'after working with us SBI made sure......'. Is there any way for me to petition SBI top unencrypt my characters to upload the data? 

If thats through a normal support ticket, could you then inform me what my request to SBI specifically should be?

**Comment by Mcgeneral1987** [comment]
You are correct. The account in question was only 2 yrs old and only had 1 premium period with a starterpack. I asked my friend if he could try with an account that was in the original beta 7 yrs ago and had multiple premium purchases. It does work for him. Gonna close the ticket as it's a 'known issue'.
