### ISSUE TITLE
Coming to EU?

### ISSUE THREAD

**Issue by Akizmostr** [ao-data/albiondata-client#92]
Hello everyone. Can you please tell me if you are planning to add a new API server for the Europe launch?

**Comment by phendryx** [comment]
Yes, there will be support for the Europe server. I will be setting up related services in the next few days. The ingest endpoints will be disabled April 23rd and AODP data for the EU sever will be wiped. The ingest endpoints will be turned back on, on the morning of April 24th. 

The website will contain info about the api endpoint (will likely be europe...com) and NATS port somewhere between now and the 24th.

**Comment by Akizmostr** [comment]
Thank you so much for your answer!
