### ISSUE TITLE
Client dosnt work for me (Mac)

### ISSUE THREAD

**Issue by Sc0ut3** [ao-data/albiondata-client#93]
Wenn i launch the "albiondata-client-exectuable" it gives me this messages under info:
PANI[2024-04-13T15:20:41+02:00] utun3: You don't have permission to capture on that device ((cannot open BPF device) /dev/bpf0: Permission denied) 
panic: (*logrus.Entry) 0xc0002521c0

**Comment by phendryx** [comment]
https://www.albion-online-data.com/#macoslinux-needs-sudo
