### ISSUE TITLE
Prices are not updating on Europe

### ISSUE THREAD

**Issue by Akizmostr** [ao-data/albiondata-client#99]
I am currently trying to retreive prices from https://europe.albion-online-data.com/api/v2/stats/prices and update them using the albion data client, but the prices are not updating despite the logs indicating that the prices were sent. 
Here is a screenshot of the game screen and logs
![image](https://github.com/ao-data/albiondata-client/assets/59568233/65a88c3b-b4e1-48a7-b2fe-bfd809e8c612)

Response from https://europe.albion-online-data.com/api/v2/stats/prices/T4_METALBAR.xml?locations=Thetford

```<ArrayOfMarketResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<MarketResponse>
<ItemTypeId>T4_METALBAR</ItemTypeId>
<City>Thetford</City>
<QualityLevel>1</QualityLevel>
<SellPriceMin>0</SellPriceMin>
<SellPriceMinDate>0001-01-01T00:00:00</SellPriceMinDate>
<SellPriceMax>0</SellPriceMax>
<SellPriceMaxDate>0001-01-01T00:00:00</SellPriceMaxDate>
<BuyPriceMin>0</BuyPriceMin>
<BuyPriceMinDate>0001-01-01T00:00:00</BuyPriceMinDate>
<BuyPriceMax>0</BuyPriceMax>
<BuyPriceMaxDate>0001-01-01T00:00:00</BuyPriceMaxDate>
</MarketResponse>
</ArrayOfMarketResponse>
```

Am I doing something wrong?

**Comment by phendryx** [comment]
You're hitting the wrong API. In the screenshot, it says it's updating average stats, which is history. If you goto https://europe.albion-online-data.com/api/v2/stats/history/T4_METALBAR.xml, there's data there. Right now, it seems most people are blocked/encrypted for the prices api which shows "Sending X market offers to ingest" (picture attached).

![image](https://github.com/ao-data/albiondata-client/assets/482311/4d9a1501-e3df-45a5-a5eb-cdc38f015d81)

**Comment by Akizmostr** [comment]
As far as I understand, the problem is known and will be fixed?

**Comment by phendryx** [comment]
No, there's no problem and nothing to be fixed. Blocked/encrypted data is something SBI did a few months back. There's nothing we can do to fix that.

There's some magic combination of data points about your account/toon that disables encryption and allows live prices to flow again. Not sure if you're on the AODP Discord or not, but there's explanations there. The AODP website needs to be updated to have some of that data, but most people end up asking about it in Discord.
